#!/usr/bin/env ruby

git_bundles = [ 
  "http://github.com/scrooloose/nerdtree.git",
  "https://github.com/altercation/vim-colors-solarized.git",
]

hg_bundles = [
]

vim_org_scripts = [
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

hg_bundles.each do |url|
  dir = url.split('/').last.sub(/\.hg/, '')
  puts "  Unpacking #{url} into #{dir}"
  `hg clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".hg"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  `curl -o #{local_file} -L http://www.vim.org/scripts/download_script.php?src_id=#{script_id}`
end
